/* ============================================================================
   SQL JOIN INTERVIEW QUESTIONS  -  Junior Data Engineer
   Schema (see Joins_Practise.sql):
     customers, categories, products, orders, order_items,
     payments(1:1 order), shipments(1:1 order), reviews
   Revenue = order_items.quantity * order_items.price_each
   66 questions | Basic -> Business -> JOIN+Concepts -> Advanced -> Classic
   Questions describe the business need; choose the best join yourself.
   ============================================================================ */


/* ============================================================================
   SECTION 1 - BASIC JOINS  (Q1 - Q15)
   ============================================================================ */

-- Question 1
-- Show each customer together with the orders they have placed.

------------------------------------------------------------

-- Question 2
-- For every order, display the order id, order date, customer name and city.

------------------------------------------------------------

-- Question 3
-- Show each product together with the name of the category it belongs to.

------------------------------------------------------------

-- Question 4
-- For a regional grouping analysis, list pairs of customers who live in the
-- same city.

------------------------------------------------------------

-- Question 5
-- Display each order with its shipment status. Include orders that have not
-- been shipped yet.

------------------------------------------------------------

-- Question 6
-- Show the payment mode used for each order. Include orders that have no
-- payment recorded.

------------------------------------------------------------

-- Question 7
-- Produce a list of all customers and their orders. Customers who have not
-- placed any order should still appear.

------------------------------------------------------------

-- Question 8
-- For each order line, display the order id, product name and quantity.

------------------------------------------------------------

-- Question 9
-- Show each product with its category name, price and stock quantity.

------------------------------------------------------------

-- Question 10
-- The marketing team needs a re-engagement list: find all customers who have
-- never placed an order.

------------------------------------------------------------

-- Question 11
-- List every category along with the products in it. Categories that contain
-- no products should still appear.

------------------------------------------------------------

-- Question 12
-- To plan a full catalog mailing, generate every possible pairing of a
-- customer with a product.

------------------------------------------------------------

-- Question 13
-- Show each product along with the reviews it has received. Include products
-- that have no reviews.

------------------------------------------------------------

-- Question 14
-- List all orders placed by customers located in 'Chennai'.

------------------------------------------------------------

-- Question 15
-- Show each review with the customer name, the product name and the rating.


/* ============================================================================
   SECTION 2 - BUSINESS-ORIENTED JOIN QUERIES  (Q16 - Q35)
   ============================================================================ */

-- Question 16
-- Report the total number of orders placed by every customer, including
-- customers who have placed none.

------------------------------------------------------------

-- Question 17
-- Calculate the total amount spent by each customer.

------------------------------------------------------------

-- Question 18
-- Calculate the total revenue generated by each product.

------------------------------------------------------------

-- Question 19
-- Calculate the total revenue generated by each category.

------------------------------------------------------------

-- Question 20
-- Identify the top 5 customers by total spending.

------------------------------------------------------------

-- Question 21
-- Identify the best-selling product measured by total quantity sold.

------------------------------------------------------------

-- Question 22
-- Calculate the average rating for each product.

------------------------------------------------------------

-- Question 23
-- The inventory team wants a dead-stock report: list all products that have
-- never been sold.

------------------------------------------------------------

-- Question 24
-- Find categories that currently have no products.

------------------------------------------------------------

-- Question 25
-- Find customers who have never written a review.

------------------------------------------------------------

-- Question 26
-- Find products that have never received a review.

------------------------------------------------------------

-- Question 27
-- Find orders that have no payment recorded.

------------------------------------------------------------

-- Question 28
-- Find orders that have not been shipped.

------------------------------------------------------------

-- Question 29
-- Calculate the total revenue generated for each order status.

------------------------------------------------------------

-- Question 30
-- Identify the city that has generated the highest total revenue.

------------------------------------------------------------

-- Question 31
-- Calculate the total revenue generated in each city.

------------------------------------------------------------

-- Question 32
-- Calculate the total amount collected through each payment mode.

------------------------------------------------------------

-- Question 33
-- List the customers who have purchased products from the 'Electronics'
-- category.

------------------------------------------------------------

-- Question 34
-- Find products that are in stock but have never been sold.

------------------------------------------------------------

-- Question 35
-- Find cancelled orders that still have a payment recorded against them.


/* ============================================================================
   SECTION 3 - JOIN + SQL CONCEPTS  (Q36 - Q50)
   ============================================================================ */

-- Question 36
-- Find repeat customers: those who have placed more than one order.

------------------------------------------------------------

-- Question 37
-- Find customers who have purchased products from more than one category.

------------------------------------------------------------

-- Question 38
-- Rank customers by their total spend, from highest to lowest.

------------------------------------------------------------

-- Question 39
-- Classify every customer as 'Active' if they have placed at least one order,
-- otherwise 'Inactive'.

------------------------------------------------------------

-- Question 40
-- Show each order with its customer name and payment status. When an order has
-- no payment, display 'No Payment'.

------------------------------------------------------------

-- Question 41
-- Report the total amount spent by every customer, showing 0 for customers
-- who have spent nothing.

------------------------------------------------------------

-- Question 42
-- Produce a report of every customer with the date of their most recent order.
-- Customers with no orders should show 'No Orders'.

------------------------------------------------------------

-- Question 43
-- List the customer name, order id and order status for all orders placed in
-- May 2026.

------------------------------------------------------------

-- Question 44
-- Calculate the average order value for each customer.

------------------------------------------------------------

-- Question 45
-- Report the monthly revenue trend (revenue grouped by order month).

------------------------------------------------------------

-- Question 46
-- Report the top 2 categories by total revenue.

------------------------------------------------------------

-- Question 47
-- For each payment status, report the number of payments and the total amount
-- collected.

------------------------------------------------------------

-- Question 48
-- Find products that generated revenue but have an average rating below 4.

------------------------------------------------------------

-- Question 49
-- For each order, label its total value as 'High' when it is 50000 or more,
-- otherwise 'Low'.

------------------------------------------------------------

-- Question 50
-- Calculate the percentage contribution of each category to the total revenue.


/* ============================================================================
   SECTION 4 - ADVANCED JUNIOR-LEVEL JOIN QUESTIONS  (Q51 - Q60)
   ============================================================================ */

-- Question 51
-- Build a complete sales report showing customer name, order id, product name,
-- category name, quantity, line total, payment status and shipment status.

------------------------------------------------------------

-- Question 52
-- Find customers whose total spend is greater than the average total spend
-- across all customers.

------------------------------------------------------------

-- Question 53
-- Report the total revenue per category and return only categories whose
-- revenue is above 50000.

------------------------------------------------------------

-- Question 54
-- List the products that have been ordered at least once.

------------------------------------------------------------

-- Question 55
-- Find customers who have placed at least one order but have never written a
-- review.

------------------------------------------------------------

-- Question 56
-- Identify a fulfilment gap: find orders that have been paid but have not yet
-- been shipped.

------------------------------------------------------------

-- Question 57
-- Find products that have been reviewed but have never been ordered.

------------------------------------------------------------

-- Question 58
-- Calculate the total revenue per customer, making sure the amount is not
-- inflated by the one-to-many relationship between orders and order items.

------------------------------------------------------------

-- Question 59
-- For every shipped-and-delivered order, calculate the number of days taken to
-- deliver it.

------------------------------------------------------------

-- Question 60
-- Build a customer 360 summary showing, for every customer, the total number
-- of orders, total amount spent, number of reviews written and average rating
-- given. Include customers with no activity.


/* ============================================================================
   SECTION 5 - CLASSIC INTERVIEW PROBLEMS  (Q61 - Q66)
   ============================================================================ */

-- Question 61
-- Find the second highest spending customer.

------------------------------------------------------------

-- Question 62
-- Find the top-selling product (by quantity) in each category.

------------------------------------------------------------

-- Question 63
-- Return the latest order (all order columns) for each customer.

------------------------------------------------------------

-- Question 64
-- Market-basket analysis: find pairs of products that were bought together in
-- the same order, and how often each pair occurs.

------------------------------------------------------------

-- Question 65
-- Calculate each customer's percentage contribution to the total revenue.

------------------------------------------------------------

-- Question 66
-- Find customers whose average order value is above the overall average order
-- value.
